sudo: required

language: bash

services:
  - docker

before_install:
  - docker build -t docker.uncharted.software/salt-test .
  - docker run -e "GRADLE_OPTS=-Dorg.gradle.daemon=false" -e "CI_NAME=travis_ci" --rm docker.uncharted.software/salt-test coverage coveralls

script: echo "All Done!"
