sudo: required

language: bash

services:
  - docker

before_install:
  - docker build -t docker.uncharted.software/salt-test .
  - docker run -e "GRADLE_OPTS=-Dorg.gradle.daemon=false" --rm docker.uncharted.software/salt-test

script: echo "All Done!"
